export const FETCH_MESSAGES = 'SUCCESS_FETCH_MESSAGES';
export const LOADING_FETCH_MESSAGES = 'LOADING_FETCH_MESSAGES';
export const STOP_LOADING_FETCH_MESSAGES = 'STOP_LOADING_FETCH_MESSAGES';
export const SUCCESS_CHANGE_MESSAGE_STATUS = 'SUCCESS_CHANGE_MESSAGE_STATUS';
export const LOADING_CHANGE_MESSAGE_STATUS = 'LOADING_CHANGE_MESSAGE_STATUS';
export const STOP_CHANGE_MESSAGE_STATUS = 'STOP_CHANGE_MESSAGE_STATUS';
export const SET_CURRENT_VOICEMAIL_BOX = 'SET_CURRENT_VOICEMAIL_BOX';
